### ISSUE TITLE
Change the distutils to setuptools, the distutils is no longer supported

### ISSUE THREAD

**Issue by lxj1999** [LironSimon/SciMED#8]
#!/usr/bin/env python

from setuptools import setup, find_packages

setup(name='SciMED',
      version='1.0',
      description='A computational framework for finding symbolic expressions from physical datasets.',
      author='Liron Simon Keren, Alex Liberzon, Teddy Lazebnik',
      author_email='lazebnik.teddy@gmail.com',
      url='https://github.com/LironSimon/SciMED',
      packages=find_packages(),
     )

**Comment by teddy4445** [comment]
@LironSimon may you please fix this one?

**Comment by LironSimon** [comment]
Done. Thanks
